--
-- PostgreSQL database dump
--

-- Dumped from database version 15.10 (Debian 15.10-0+deb12u1)
-- Dumped by pg_dump version 15.10 (Debian 15.10-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: "$user", public; Type: SCHEMA; Schema: -; Owner: guessholedbuser
--

CREATE SCHEMA """$user"", public";


ALTER SCHEMA """$user"", public" OWNER TO guessholedbuser;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: guessholedbuser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO guessholedbuser;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: guessholedbuser
--

COMMENT ON SCHEMA public IS '';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_instance; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.game_instance (
    id uuid NOT NULL,
    game_type character varying(50) NOT NULL
);


ALTER TABLE public.game_instance OWNER TO guessholedbuser;

--
-- Name: game_instance_player; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.game_instance_player (
    id uuid NOT NULL,
    game_instance_id uuid NOT NULL,
    player_id uuid NOT NULL
);


ALTER TABLE public.game_instance_player OWNER TO guessholedbuser;

--
-- Name: game_state; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.game_state (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    lobby_state character varying(255) NOT NULL,
    round_id uuid,
    lobby_id uuid NOT NULL,
    game_instance_id uuid
);


ALTER TABLE public.game_state OWNER TO guessholedbuser;

--
-- Name: guesses; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.guesses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    player_id uuid NOT NULL,
    round_id uuid NOT NULL,
    game_instance_id uuid NOT NULL,
    latitude numeric(10,6) NOT NULL,
    longitude numeric(10,6) NOT NULL,
    distance_km double precision,
    "timestamp" timestamp with time zone NOT NULL,
    score integer,
    round_duration integer,
    guess_time integer
);


ALTER TABLE public.guesses OWNER TO guessholedbuser;

--
-- Name: COLUMN guesses.id; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.guesses.id IS 'Primary key with UUID automatically generated by the database';


--
-- Name: lobbies; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.lobbies (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    privacy character varying(20) NOT NULL
);


ALTER TABLE public.lobbies OWNER TO guessholedbuser;

--
-- Name: players; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.players (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    lobby_id uuid NOT NULL,
    is_host boolean DEFAULT false NOT NULL,
    avatar character varying(50) DEFAULT 'avatar1'::character varying,
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.players OWNER TO guessholedbuser;

--
-- Name: round; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.round (
    id uuid NOT NULL,
    game_instance_id uuid NOT NULL,
    round_order integer NOT NULL,
    youtube_video_id character varying(20) NOT NULL,
    start_time_seconds integer NOT NULL,
    duration_seconds integer NOT NULL,
    latitude numeric(8,6),
    longitude numeric(9,6)
);


ALTER TABLE public.round OWNER TO guessholedbuser;

--
-- Name: round_template; Type: TABLE; Schema: public; Owner: guessholedbuser
--

CREATE TABLE public.round_template (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source character varying(255) NOT NULL,
    youtube_video_id character varying(100) NOT NULL,
    start_time integer NOT NULL,
    latitude numeric(10,6) NOT NULL,
    longitude numeric(10,6) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    approve_at timestamp with time zone,
    video_length integer
);


ALTER TABLE public.round_template OWNER TO guessholedbuser;

--
-- Name: TABLE round_template; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON TABLE public.round_template IS 'Templates for rounds that can be used to create game instances';


--
-- Name: COLUMN round_template.id; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.round_template.id IS 'Unique identifier for the round template';


--
-- Name: COLUMN round_template.source; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.round_template.source IS 'Source of the round template data';


--
-- Name: COLUMN round_template.youtube_video_id; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.round_template.youtube_video_id IS 'YouTube video ID used for this round';


--
-- Name: COLUMN round_template.start_time; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.round_template.start_time IS 'Start time in seconds within the YouTube video';


--
-- Name: COLUMN round_template.latitude; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.round_template.latitude IS 'Latitude of the location shown in the video';


--
-- Name: COLUMN round_template.longitude; Type: COMMENT; Schema: public; Owner: guessholedbuser
--

COMMENT ON COLUMN public.round_template.longitude IS 'Longitude of the location shown in the video';


--
-- Name: game_instance game_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_instance
    ADD CONSTRAINT game_instance_pkey PRIMARY KEY (id);


--
-- Name: game_instance_player game_instance_player_game_instance_id_player_id_key; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_instance_player
    ADD CONSTRAINT game_instance_player_game_instance_id_player_id_key UNIQUE (game_instance_id, player_id);


--
-- Name: game_instance_player game_instance_player_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_instance_player
    ADD CONSTRAINT game_instance_player_pkey PRIMARY KEY (id);


--
-- Name: game_state game_state_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_state
    ADD CONSTRAINT game_state_pkey PRIMARY KEY (id);


--
-- Name: guesses guesses_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT guesses_pkey PRIMARY KEY (id);


--
-- Name: lobbies lobbies_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.lobbies
    ADD CONSTRAINT lobbies_pkey PRIMARY KEY (id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: round round_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT round_pkey PRIMARY KEY (id);


--
-- Name: round_template round_template_pkey; Type: CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.round_template
    ADD CONSTRAINT round_template_pkey PRIMARY KEY (id);



--
-- Name: idx_game_instance_player_game_instance_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_game_instance_player_game_instance_id ON public.game_instance_player USING btree (game_instance_id);


--
-- Name: idx_game_instance_player_player_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_game_instance_player_player_id ON public.game_instance_player USING btree (player_id);


--
-- Name: idx_game_state_lobby_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_game_state_lobby_id ON public.game_state USING btree (lobby_id);


--
-- Name: idx_guesses_game_instance_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_guesses_game_instance_id ON public.guesses USING btree (game_instance_id);


--
-- Name: idx_guesses_player_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_guesses_player_id ON public.guesses USING btree (player_id);


--
-- Name: idx_guesses_round_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_guesses_round_id ON public.guesses USING btree (round_id);


--
-- Name: idx_round_game_instance_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_round_game_instance_id ON public.round USING btree (game_instance_id);


--
-- Name: idx_round_template_coordinates; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_round_template_coordinates ON public.round_template USING btree (latitude, longitude);


--
-- Name: idx_round_template_source; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_round_template_source ON public.round_template USING btree (source);


--
-- Name: idx_round_template_youtube_id; Type: INDEX; Schema: public; Owner: guessholedbuser
--

CREATE INDEX idx_round_template_youtube_id ON public.round_template USING btree (youtube_video_id);


--
-- Name: guesses fk_guesses_game_instance; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT fk_guesses_game_instance FOREIGN KEY (game_instance_id) REFERENCES public.game_instance(id) ON DELETE CASCADE;


--
-- Name: guesses fk_guesses_player; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT fk_guesses_player FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;


--
-- Name: guesses fk_guesses_round; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT fk_guesses_round FOREIGN KEY (round_id) REFERENCES public.round(id) ON DELETE CASCADE;


--
-- Name: game_instance_player game_instance_player_game_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_instance_player
    ADD CONSTRAINT game_instance_player_game_instance_id_fkey FOREIGN KEY (game_instance_id) REFERENCES public.game_instance(id);


--
-- Name: game_instance_player game_instance_player_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_instance_player
    ADD CONSTRAINT game_instance_player_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- Name: game_state game_state_lobby_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.game_state
    ADD CONSTRAINT game_state_lobby_id_fkey FOREIGN KEY (lobby_id) REFERENCES public.lobbies(id);


--
-- Name: players players_lobby_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_lobby_id_fkey FOREIGN KEY (lobby_id) REFERENCES public.lobbies(id) ON DELETE CASCADE;


--
-- Name: round round_game_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: guessholedbuser
--

ALTER TABLE ONLY public.round
    ADD CONSTRAINT round_game_instance_id_fkey FOREIGN KEY (game_instance_id) REFERENCES public.game_instance(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: guessholedbuser
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

